### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [thomasp85/ragg#7]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in destructors like for the classes “[gradient_contour](https://github.com/thomasp85/ragg/blob/c72cf825c2b3ad0188be7e6264ccfa90e34ba553/src/agg/include/agg_span_gradient_contour.h#L77 "Destructor for gradient_contour")” and “[gradient_image](https://github.com/thomasp85/ragg/blob/c72cf825c2b3ad0188be7e6264ccfa90e34ba553/src/agg/include/agg_span_gradient_image.h#L92 "Destructor for gradient_image")”.

**Comment by thomasp85** [comment]
Thanks... I'm unlikely to change code in AGG unless it is directly wrong
